# Generated by Django 4.2.7 on 2023-11-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_viajes_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='projects.viajes'),
        ),
    ]
