# Generated by Django 4.2.7 on 2023-11-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_gastos_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='placa',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
