# Generated by Django 4.2.7 on 2023-12-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_autos_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos/'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='gastos/'),
        ),
    ]
