# Generated by Django 4.2.7 on 2023-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_autos_imagen_gastos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='soat',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='autos',
            name='tecnomecanica',
            field=models.DateField(default=None, null=True),
        ),
    ]
